import type { SeoPageContent } from "./seo-page-types";
import { RUNWAY_REPORT_FULL, RUNWAY_REPORT_PRICE_GBP } from "@shared/product";

const UNLOCK_REPORT_CTA = `Unlock full report — £${RUNWAY_REPORT_PRICE_GBP}`;

const baseAssumptions = [
  "This page is general preparation information only — not legal, employment or financial advice.",
  "Package figures should be checked against written employer information before you rely on them.",
  "Outcomes depend on your employer's process, role, and circumstances.",
];

function guidePage(
  slug: string,
  metaTitle: string,
  metaDescription: string,
  h1: string,
  badge: string,
  intro: string,
  intent: string,
  helps: string[],
  exampleTitle: string,
  exampleBody: string,
  faqs: Array<{ question: string; answer: string }>,
  variant: SeoPageContent["variant"] = "consultation",
): SeoPageContent {
  return {
    slug,
    metaTitle,
    metaDescription,
    h1,
    primaryCta: "Calculate my redundancy pay",
    primaryHref: "/wizard",
    secondaryCta: UNLOCK_REPORT_CTA,
    secondaryHref: "/free-redundancy-calculator",
    badge,
    intro,
    intent,
    helps,
    assumptions: baseAssumptions,
    example: { title: exampleTitle, body: exampleBody },
    faqs,
    variant,
  };
}

/** SEO pages referenced in App.tsx routes but missing from the main pages array. */
export const missingSeoPages: SeoPageContent[] = [
  guidePage(
    "worried-about-redundancy",
    "Worried About Redundancy? Prepare Calmly",
    "If you are worried about redundancy, organise documents, consultation questions, package assumptions and household runway scenarios calmly.",
    "Worried about redundancy?",
    "Redundancy-specific worry",
    "Redundancy worry usually means missing facts about your package, consultation dates and household runway — not the statutory figure alone. This page is for redundancy specifically (see our separate guide if your job feels at risk but redundancy has not been mentioned).",
    "Targets redundancy-anxiety searches distinct from general job-loss worry.",
    [
      "List documents and dates to confirm with HR.",
      "Estimate statutory, notice and holiday pay assumptions.",
      "Prepare calm consultation questions before meetings.",
      "Model household runway privately from your costs.",
    ],
    "Example: organise before you react",
    "Before accepting verbal figures, gather your start date, gross weekly pay, notice period and holiday balance. Those details make consultation and modelling much clearer.",
    [
      { question: "What should I do first if I am worried about redundancy?", answer: "Collect written information, confirm key dates, estimate the package and model essential household costs before making major decisions." },
      { question: "Is this legal advice?", answer: "No. This is practical preparation and private financial modelling only." },
      { question: "How is this different from worried about losing your job?", answer: "This page assumes redundancy is on the table. Our job-at-risk guide covers broader uncertainty before redundancy is mentioned." },
    ],
  ),
  guidePage(
    "at-risk-of-redundancy-calculator",
    "At Risk of Redundancy Calculator UK",
    "Model package assumptions, consultation prep and household runway if your role is at risk — private modelling from your figures.",
    "At risk of redundancy calculator",
    "At-risk modelling",
    "If your role is at risk, combine package estimates with consultation preparation and runway modelling so you know what to verify before decisions are final.",
    "This page connects at-risk searches to the free calculator and full private report.",
    [
      "Estimate statutory and package components from your assumptions.",
      "Flag gaps in notice, holiday and enhanced pay.",
      "Prepare consultation questions alongside the numbers.",
      "See baseline runway months on household costs.",
    ],
    "Example: model while consultation is open",
    "Enter your weekly pay and service, add notice and holiday assumptions, then see how many runway months the package may buy under your costs.",
    [
      { question: "Does this replace legal advice?", answer: "No. It helps you organise figures and questions privately." },
      { question: "Can I update figures later?", answer: "Yes. Update assumptions as HR confirms written details." },
      { question: "What unlocks with the paid report?", answer: "Maximiser checks, consultation prep tools, stress scenarios and a plain-English brief." },
    ],
    "consultation",
  ),
  guidePage(
    "redundancy-readiness-calculator",
    "Redundancy Readiness Calculator UK",
    "Check whether your redundancy model is complete — package assumptions, essential costs, savings and income recovery — before relying on the numbers.",
    "Redundancy readiness calculator",
    "Readiness check",
    "A readiness view helps you see whether key assumptions are entered before you treat the model as useful for planning.",
    "This page captures readiness searches and points to the free preview and full report.",
    [
      "See whether package assumptions look complete.",
      "Check essential costs and savings are entered.",
      "Understand what is still assumed vs confirmed.",
      "Move into deeper scenarios with the full report.",
    ],
    "Example: readiness before decisions",
    "If notice pay or holiday is still blank, the package total may understate what you could receive — readiness flags those gaps.",
    [
      { question: "What is redundancy readiness?", answer: "A measure of how complete your financial model is — not whether your job is safe." },
      { question: "Is the calculator free to start?", answer: "Yes. The free preview includes a baseline readiness view." },
      { question: "Does this predict redundancy?", answer: "No. It models assumptions you enter." },
    ],
    "runway",
  ),
  guidePage(
    "redundancy-consultation-defence-pack",
    "Redundancy Consultation Defence Pack",
    "Prepare for redundancy consultation by organising documents, questions, role evidence and package assumptions without promising an outcome.",
    "Redundancy consultation defence pack",
    "Consultation Defence Pack",
    "The Consultation Defence Pack in the full report organises evidence, HR questions and package assumptions into structured preparation — this page explains what to gather before you unlock it.",
    "Product-led prep page for the paid Consultation Defence Pack — not a generic rights article.",
    [
      "Organise consultation documents and dates.",
      "Prepare evidence and question banks.",
      "Clarify package assumptions before meetings.",
      "Link preparation to private runway modelling.",
    ],
    "Example: pack before the meeting",
    "Bring written selection criteria, your role history notes, holiday balance and a list of clarification questions — not just a mental total.",
    [
      { question: "Is this a legal defence pack?", answer: "No. It is practical preparation and checklists — not legal advice." },
      { question: "Where is the Consultation Defence Pack?", answer: `It unlocks in the ${RUNWAY_REPORT_FULL} (£${RUNWAY_REPORT_PRICE_GBP}, one-off) alongside maximiser checks and runway dashboards.` },
      { question: "Can I start with the free calculator?", answer: "Yes. Estimate pay first, then add preparation tools when you unlock." },
    ],
  ),
  guidePage(
    "how-to-prepare-for-redundancy-consultation",
    "How to Prepare for Redundancy Consultation",
    "Prepare for redundancy consultation with a calm checklist for documents, selection questions, alternatives and package assumptions.",
    "How to prepare for redundancy consultation",
    "Before your first meeting",
    "Use the 48 hours before your first consultation meeting to gather documents, confirm pay assumptions and write questions — not to make irreversible decisions.",
    "First-meeting preparation — distinct from ongoing consultation prep and question banks.",
    [
      "Confirm consultation dates and attendees.",
      "List selection criteria and evidence to gather.",
      "Estimate package components from written policy.",
      "Model runway impact from your household costs.",
    ],
    "Example: checklist first",
    "Before the first meeting, write down notice period, holiday balance, selection pool definition and any internal vacancy list you have been given.",
    [
      { question: "What documents should I gather?", answer: "Contract, redundancy policy, payslips, holiday records and any selection criteria documents shared by HR." },
      { question: "Should I model pay before consultation ends?", answer: "Yes, as a scenario estimate — update when figures are confirmed in writing." },
      { question: "Is this employment advice?", answer: "No. General preparation information only." },
    ],
  ),
  guidePage(
    "redundancy-consultation-preparation",
    "Redundancy Consultation Preparation",
    "Prepare for redundancy consultation by organising role evidence, selection questions, package assumptions and next-step planning.",
    "Redundancy consultation preparation",
    "Across the consultation period",
    "Preparation spans the whole consultation window: each meeting, each written follow-up and each update to your package assumptions.",
    "Ongoing consultation-period prep — not the same as a one-off checklist or question list.",
    [
      "Map the consultation timeline and your deadlines.",
      "Prepare role and performance context notes.",
      "List alternative roles and redeployment questions.",
      "Estimate package and runway privately.",
    ],
    "Example: calm preparation",
    "Create a one-page summary of dates, pay assumptions, open questions and essential monthly costs before each HR meeting.",
    [
      { question: "How is this different from legal advice?", answer: "It helps you organise information and questions — it does not assess fairness or rights." },
      { question: "Can partners use the calculator?", answer: "Yes. Household costs and partner income can be included in runway modelling." },
      { question: "What unlocks in the paid report?", answer: "Consultation Defence Pack, role protection planner and maximiser checks." },
    ],
  ),
  guidePage(
    "redundancy-consultation-checklist",
    "Redundancy Consultation Checklist",
    "Use a redundancy consultation checklist to organise questions, evidence, package figures and follow-up actions before meetings.",
    "Redundancy consultation checklist",
    "Tick-list format",
    "Work through a checklist before, during and after each consultation — documents requested, questions asked, assumptions updated and follow-ups sent.",
    "Checklist-format page — distinct from open question banks.",
    [
      "Documents to request or confirm.",
      "Questions about selection and alternatives.",
      "Package lines to verify in writing.",
      "Household runway assumptions to update.",
    ],
    "Example: tick-list before each meeting",
    "After each consultation, note what was confirmed, what remains unclear and what written follow-up you requested.",
    [
      { question: "Can I print a checklist?", answer: "Use the report export tools after unlock for a downloadable summary of your assumptions." },
      { question: "Does the checklist guarantee an outcome?", answer: "No. It is organisation only." },
      { question: "Where do I start?", answer: "Free calculator for pay estimate, then unlock for full prep tools." },
    ],
  ),
  guidePage(
    "how-to-protect-yourself-during-redundancy-consultation",
    "How to Protect Yourself During Redundancy Consultation",
    "Organise documents, evidence, questions and package assumptions during redundancy consultation without promising an outcome.",
    "How to protect yourself during redundancy consultation",
    "During consultation",
    "Protection here means organised preparation — written records, calm questions and verified figures — not confrontation.",
    "Supports people searching for self-protection during consultation.",
    [
      "Keep written notes of what HR says.",
      "Request package breakdowns in writing.",
      "Avoid relying on verbal totals alone.",
      "Model financial impact before accepting terms.",
    ],
    "Example: written follow-up",
    "After a meeting, email HR to confirm the selection pool, criteria and payment dates you understood — and ask them to correct anything inaccurate.",
    [
      { question: "Should I record meetings?", answer: "Check your employer's policy and local law. This site does not provide legal guidance on recording." },
      { question: "Can I challenge selection here?", answer: "This page helps you prepare questions and evidence — not assess legal merit." },
      { question: "What professional help exists?", answer: "ACAS, unions, Citizens Advice or employment solicitors may help with rights questions." },
    ],
  ),
  guidePage(
    "how-to-avoid-being-selected-for-redundancy",
    "How to Avoid Being Selected for Redundancy | Prep Guide",
    "Understand selection criteria and organise evidence, questions and package assumptions before redundancy consultation.",
    "How to avoid being selected for redundancy",
    "Selection preparation",
    "No tool can guarantee avoidance. Preparation means understanding criteria, gathering evidence and asking clear questions early.",
    "Captures high-intent selection searches with realistic boundaries.",
    [
      "Understand stated selection criteria.",
      "Gather evidence relevant to those criteria.",
      "Explore redeployment and alternative roles.",
      "Model financial impact if selection proceeds.",
    ],
    "Example: evidence folder",
    "Keep training records, project outcomes and role descriptions that relate to the criteria HR has shared.",
    [
      { question: "Can this tool keep my job safe?", answer: "No. It helps you prepare and model finances — not influence selection outcomes." },
      { question: "What should I ask about criteria?", answer: "Ask for written criteria, weighting, scoring method and your scores if used." },
      { question: "Is redeployment part of avoidance?", answer: "Alternative roles may be discussed during consultation — prepare questions about internal vacancies." },
    ],
  ),
  guidePage(
    "redundancy-selection-criteria",
    "Redundancy Selection Criteria | UK Preparation Guide",
    "Understand common redundancy selection criteria and prepare evidence and questions before consultation.",
    "Redundancy selection criteria",
    "Selection criteria",
    "Selection criteria define how roles are compared. Understanding them helps you prepare evidence and questions — not predict outcomes.",
    "Selection criteria preparation guide.",
    [
      "Request written selection criteria from HR.",
      "Map your evidence to each criterion.",
      "Prepare questions about weighting and scoring.",
      "Model package and runway alongside preparation.",
    ],
    "Example: criteria on paper",
    "If criteria mention skills, attendance and performance, list what evidence you hold for each and what is still unclear.",
    [
      { question: "Are selection criteria always fair?", answer: "Fairness is a legal question — this page only supports preparation." },
      { question: "Can criteria change?", answer: "Ask HR to confirm whether criteria are fixed for the pool and how changes are communicated." },
      { question: "Where can I model pay?", answer: "Use the free UK redundancy calculator on this site." },
    ],
  ),
  guidePage(
    "redundancy-selection-score",
    "Redundancy Selection Score | Preparation Guide",
    "Prepare questions about redundancy selection scoring and organise evidence before consultation without assessing fairness.",
    "Redundancy selection score",
    "Selection scoring",
    "If scoring is used, you need clarity on inputs, weighting and your recorded scores — prepare questions, not arguments.",
    "Selection score preparation page.",
    [
      "Ask whether a scoring matrix is used.",
      "Request your scores and supporting notes.",
      "Challenge unclear inputs with calm questions.",
      "Keep financial modelling separate from scoring disputes.",
    ],
    "Example: score transparency",
    "Ask HR to show how attendance, skills and performance scores combined in your case and whether anyone reviewed the total.",
    [
      { question: "Can I recalculate my score here?", answer: "No. This site does not replicate employer scoring systems." },
      { question: "What if scores look wrong?", answer: "Ask for written clarification and keep records — consider professional advice for rights questions." },
      { question: "Does preparation help financially?", answer: "Yes — parallel runway modelling helps regardless of selection outcome." },
    ],
  ),
  guidePage(
    "redundancy-selection-matrix",
    "Redundancy Selection Matrix | Criteria Prep",
    "Use a selection matrix preparation guide to organise criteria, evidence, scores and consultation questions.",
    "Redundancy selection matrix",
    "Selection matrix",
    "A matrix is a structured way employers compare roles. Prepare by understanding rows, columns and what evidence supports each cell.",
    "Matrix-style selection prep.",
    [
      "Request a copy of the matrix or scoring sheet.",
      "Map your evidence to each criterion.",
      "List clarification questions per row.",
      "Model redundancy pay assumptions in parallel.",
    ],
    "Example: matrix questions",
    "Ask which criteria were weighted most heavily and whether subjective scoring was moderated by a second reviewer.",
    [
      { question: "Is every employer matrix the same?", answer: "No. Processes vary — always ask for your employer's written approach." },
      { question: "Can I export my preparation?", answer: "Paid report tools include consultation and position preparation exports." },
      { question: "Free starting point?", answer: "Yes — statutory and package estimate on the free calculator." },
    ],
  ),
  guidePage(
    "how-to-challenge-redundancy-selection",
    "How to Challenge Redundancy Selection | Prep Guide",
    "Prepare evidence and questions if you want to query redundancy selection, without rights assessment or outcome promises.",
    "How to challenge redundancy selection",
    "Query selection",
    "Challenging selection starts with clarity — criteria, scores, process steps and written records — not immediate escalation.",
    "Challenge preparation with compliance boundaries.",
    [
      "Document the selection process step by step.",
      "List factual discrepancies to raise calmly.",
      "Ask for written responses to key questions.",
      "Model finances while process continues.",
    ],
    "Example: factual challenge",
    "If attendance scoring ignored approved leave, ask HR in writing how that period was treated in the matrix.",
    [
      { question: "Is this legal representation?", answer: "No. Consider ACAS, a union or a solicitor for formal challenges." },
      { question: "Should I sign anything while challenging?", answer: "Take time to review settlement documents — this site does not advise on signing." },
      { question: "Can I still use the calculator?", answer: "Yes. Modelling helps you understand financial impact while you prepare process questions." },
    ],
  ),
  guidePage(
    "redundancy-selection-criteria-examples",
    "Redundancy Selection Criteria Examples",
    "Review common redundancy selection criteria examples and prepare evidence questions before consultation.",
    "Redundancy selection criteria examples",
    "Criteria examples",
    "Examples include skills, performance, attendance, disciplinary records and flexibility — always confirm what your employer actually uses.",
    "Examples page for selection criteria cluster.",
    [
      "Compare employer criteria to common examples.",
      "Identify evidence you can gather for each.",
      "Prepare questions where criteria are vague.",
      "Link preparation to package modelling.",
    ],
    "Example: skills vs attendance",
    "If both skills and attendance appear, ask how much each contributes and whether recent training is reflected.",
    [
      { question: "Are these examples legal standards?", answer: "No. They illustrate common themes only." },
      { question: "What evidence helps most?", answer: "Written records tied to the criteria HR published for your pool." },
      { question: "Next step financially?", answer: "Model package and runway on the free calculator." },
    ],
  ),
  guidePage(
    "what-evidence-to-prepare-for-redundancy-consultation",
    "What Evidence to Prepare for Redundancy Consultation",
    "Organise role evidence, selection criteria notes, performance context, skills records and attendance information before consultation.",
    "What evidence to prepare for redundancy consultation",
    "Evidence prep",
    "Evidence supports calm questions — role history, training, objectives, attendance context and selection criteria notes.",
    "Evidence preparation guide.",
    [
      "Role description and recent objectives.",
      "Training and qualification records.",
      "Attendance context including approved leave.",
      "Selection criteria and scoring notes from HR.",
    ],
    "Example: evidence bundle",
    "Create a folder with PDFs of appraisals, project summaries and HR emails about the redundancy pool.",
    [
      { question: "Should I send evidence before meetings?", answer: "Follow HR instructions — keep copies for yourself regardless." },
      { question: "Does evidence change statutory pay?", answer: "Statutory pay follows service and age rules — evidence mainly supports selection and consultation questions." },
      { question: "Paid tools for consultation?", answer: "Consultation Defence Pack unlocks in the full report." },
    ],
  ),
  guidePage(
    "redundancy-performance-selection-criteria",
    "Redundancy Performance Selection Criteria",
    "Prepare evidence and questions where performance is mentioned in redundancy selection criteria.",
    "Redundancy performance selection criteria",
    "Performance criteria",
    "When performance is a criterion, gather appraisals, objectives and examples of delivery — then ask how scores were applied.",
    "Performance-related selection prep.",
    [
      "Collect recent performance reviews.",
      "List objectives met since last review.",
      "Ask how performance was scored in the matrix.",
      "Model financial scenarios in parallel.",
    ],
    "Example: performance evidence",
    "If you exceeded sales targets, keep dashboards or emails confirming results and ask how they were weighted.",
    [
      { question: "Can old appraisals be ignored?", answer: "Ask HR which review period was used and why." },
      { question: "Is this HR advice?", answer: "No. Preparation information only." },
      { question: "Free calculator?", answer: "Yes — start with statutory and package estimates." },
    ],
  ),
  guidePage(
    "redundancy-skills-selection-criteria",
    "Redundancy Skills Selection Criteria",
    "Prepare skills evidence and consultation questions where skills, qualifications or experience are part of redundancy selection.",
    "Redundancy skills selection criteria",
    "Skills criteria",
    "Skills criteria may include qualifications, certifications and experience — map what you have against what HR published.",
    "Skills-based selection prep.",
    [
      "List qualifications relevant to the role.",
      "Document training completed in the last 12–24 months.",
      "Ask how skills were assessed vs role requirements.",
      "Explore redeployment where skills transfer.",
    ],
    "Example: skills gap questions",
    "If HR cites a skills gap, ask which specific skills were missing and whether training was considered before selection.",
    [
      { question: "Do skills affect statutory pay?", answer: "Statutory pay does not depend on skills — skills matter for selection and redeployment questions." },
      { question: "Alternative roles?", answer: "See redeployment preparation pages in this guide cluster." },
      { question: "Runway modelling?", answer: "Use household costs in the calculator to see months of cover." },
    ],
  ),
  guidePage(
    "redundancy-attendance-selection-criteria",
    "Redundancy Attendance Selection Criteria",
    "Prepare attendance context and consultation questions where attendance is included in redundancy selection criteria.",
    "Redundancy attendance selection criteria",
    "Attendance criteria",
    "Attendance scoring should reflect approved leave and disability-related absence correctly — prepare context and ask for methodology.",
    "Attendance-related selection prep.",
    [
      "Gather attendance records and approved leave.",
      "Note disability or carer leave context where relevant.",
      "Ask how absences were weighted in scoring.",
      "Keep financial modelling up to date.",
    ],
    "Example: approved leave",
    "If parental or sick leave was counted as absence, ask HR how policy treats statutory leave in the matrix.",
    [
      { question: "Is attendance always used?", answer: "Only if your employer published it as a criterion — confirm in writing." },
      { question: "Rights questions?", answer: "Speak to ACAS, a union or a solicitor for discrimination or disability rights queries." },
      { question: "Calculator start?", answer: "Free statutory estimate at /free-redundancy-calculator." },
    ],
  ),
  guidePage(
    "suitable-alternative-employment-redundancy",
    "Suitable Alternative Employment Redundancy | Prep Guide",
    "Prepare questions about suitable alternative employment, redeployment options, role fit and trial-period details before consultation.",
    "Suitable alternative employment redundancy",
    "Alternative employment",
    "Suitable alternative employment may affect redundancy entitlement — prepare questions about role fit, terms and trial periods.",
    "SAE preparation guide.",
    [
      "List alternative roles offered or mentioned.",
      "Compare pay, location and duties calmly.",
      "Ask about trial periods and training.",
      "Model finances for accept vs decline scenarios.",
    ],
    "Example: role comparison",
    "Create a table of old vs new role for pay, commute, hours and skills required before deciding whether to ask more questions.",
    [
      { question: "Can this site decide if a role is suitable?", answer: "No. It helps you prepare questions and model financial differences." },
      { question: "What is a trial period?", answer: "Employers may offer a trial in a new role — ask for written terms and length." },
      { question: "Model both outcomes?", answer: "Yes — use payout scenarios in the paid report." },
    ],
  ),
  guidePage(
    "alternative-role-redundancy",
    "Alternative Role Redundancy | Questions to Prepare",
    "Organise alternative role details, role-fit questions, pay assumptions and consultation notes before redundancy decisions.",
    "Alternative role redundancy",
    "Evaluating one offer",
    "When HR proposes a specific alternative role, compare duties, pay, location and trial terms before you respond — one role at a time.",
    "Single-offer evaluation — distinct from redeployment search and vacancy tracking.",
    [
      "Capture job title, pay and location for each option.",
      "List skills gaps and training offered.",
      "Prepare questions about probation or trial terms.",
      "Model household impact of each option.",
    ],
    "Example: questions list",
    "Ask whether the alternative role is on the same grade, whether redundancy pay still applies if you decline, and what deadline applies.",
    [
      { question: "Must I accept an alternative role?", answer: "That depends on employment law and your situation — seek professional advice for personal decisions." },
      { question: "Can I model pay differences?", answer: "Yes — enter different income assumptions in the runway model." },
      { question: "Free preview?", answer: "Yes — start on the wizard without payment." },
    ],
  ),
  guidePage(
    "redeployment-redundancy",
    "Redeployment Redundancy | Alternative Role Prep",
    "Prepare for redeployment conversations by organising vacancies, role-fit evidence, skills, questions and package assumptions.",
    "Redeployment redundancy",
    "Employer redeployment process",
    "Redeployment is the employer-led process of matching you to internal vacancies during consultation — track vacancies, deadlines and HR responses systematically.",
    "Process-focused redeployment page — not the same as evaluating one alternative-role offer.",
    [
      "Track internal vacancies and closing dates.",
      "Prepare CVs tailored to internal roles.",
      "Ask how redeployment interacts with selection.",
      "Model finances if redeployment fails.",
    ],
    "Example: vacancy log",
    "Keep a spreadsheet of vacancy IDs, hiring managers, deadlines and whether you applied or were considered.",
    [
      { question: "Does redeployment guarantee a role?", answer: "No. Preparation helps you engage with the process calmly." },
      { question: "HR questions?", answer: "Use the alternative employment questions page for prompt ideas." },
      { question: "Financial planning?", answer: "Model redundancy package and runway alongside redeployment efforts." },
    ],
  ),
  guidePage(
    "redundancy-alternative-employment-questions",
    "Redundancy Alternative Employment Questions",
    "Prepare calm questions about alternative employment, redeployment, vacancy details, role terms, trial periods and next steps.",
    "Redundancy alternative employment questions",
    "Questions bank",
    "Good questions clarify role terms, trial periods, pay, location and what happens if you decline — without committing under pressure.",
    "Question bank for alternative employment.",
    [
      "Questions about role duties and grade.",
      "Questions about pay, benefits and location.",
      "Questions about trial periods and training.",
      "Questions about timing if you need to decide.",
    ],
    "Example: deadline question",
    "Ask how long you have to consider an alternative role and whether redundancy pay changes if you decline.",
    [
      { question: "Can I get these in the paid report?", answer: "Consultation and package clarification tools include HR question prompts." },
      { question: "Is this legal advice?", answer: "No. Question ideas for preparation only." },
      { question: "Start modelling?", answer: "Use the free calculator first." },
    ],
  ),
  guidePage(
    "internal-vacancies-redundancy",
    "Internal Vacancies During Redundancy | Prep Guide",
    "Track internal vacancies, redeployment options, deadlines, role-fit evidence and questions during redundancy consultation.",
    "Internal vacancies during redundancy",
    "Internal vacancies",
    "During redundancy, internal vacancies may be part of redeployment — track them systematically.",
    "Internal vacancies tracking prep.",
    [
      "List vacancies in your employer's portal.",
      "Note deadlines and contact points.",
      "Match your skills to each vacancy.",
      "Ask HR how applications are prioritised.",
    ],
    "Example: weekly review",
    "Set a weekly reminder to check the internal jobs portal and log new posts during consultation.",
    [
      { question: "Must HR tell me about vacancies?", answer: "Employers often have redeployment duties — confirm your employer's policy in writing." },
      { question: "Financial backup plan?", answer: "Model runway assuming redundancy proceeds if redeployment does not work." },
      { question: "Full report value?", answer: "Unlock maximiser and consultation tools for integrated preparation." },
    ],
  ),
  guidePage(
    "redundancy-trial-period-alternative-role",
    "Redundancy Trial Period Alternative Role",
    "Prepare questions about alternative-role trial periods, training, dates, written terms and next steps during redundancy.",
    "Redundancy trial period alternative role",
    "Trial period",
    "Trial periods in alternative roles need clear written terms — duration, pay, review criteria and what happens if either side ends the trial.",
    "Trial period preparation.",
    [
      "Ask for trial length and review dates.",
      "Confirm pay and benefits during trial.",
      "Understand return rights if trial fails.",
      "Model finances for both outcomes.",
    ],
    "Example: written terms",
    "Request a written offer letter covering trial duration, training provided and notice if the trial does not work.",
    [
      { question: "Does trial period affect redundancy pay?", answer: "Ask HR how acceptance interacts with redundancy entitlement — seek advice for personal situations." },
      { question: "Can I model income change?", answer: "Yes — adjust income assumptions in the runway calculator." },
      { question: "Free start?", answer: "Yes — wizard free preview." },
    ],
  ),
  guidePage(
    "refusing-suitable-alternative-employment",
    "Refusing Suitable Alternative Employment | Prep Guide",
    "Prepare facts and questions before discussing refusal of suitable alternative employment, without deciding suitability or outcomes.",
    "Refusing suitable alternative employment",
    "Refusal preparation",
    "Before refusing an alternative role, understand financial and entitlement implications — prepare questions, not snap decisions.",
    "Refusal preparation with boundaries.",
    [
      "Compare role terms to your current role.",
      "List reasons you need clarification on.",
      "Ask HR about redundancy pay if you decline.",
      "Model household impact of each path.",
    ],
    "Example: clarify before refusing",
    "Ask whether declining affects statutory redundancy pay in your circumstances and get the answer in writing.",
    [
      { question: "Will this tell me if refusal is wise?", answer: "No. It helps you organise questions and model finances." },
      { question: "Professional advice?", answer: "Consider employment law advice before refusing if sums are large." },
      { question: "Calculator?", answer: "Model package with and without alternative role income." },
    ],
  ),
  guidePage(
    "redundancy-redeployment-checklist",
    "Redundancy Redeployment Checklist",
    "Use a redeployment checklist to organise internal vacancies, role-fit evidence, questions, trial periods and package assumptions.",
    "Redundancy redeployment checklist",
    "Redeployment checklist",
    "A redeployment checklist keeps vacancies, applications and HR responses visible while consultation continues.",
    "Redeployment checklist page.",
    [
      "Vacancy list with deadlines.",
      "Application status tracker.",
      "HR responses and open questions.",
      "Package assumptions updated weekly.",
    ],
    "Example: single tracker",
    "Use one document for vacancies, meetings and financial assumptions so nothing slips during a stressful period.",
    [
      { question: "Export checklist?", answer: "Paid report includes exportable preparation summaries." },
      { question: "Does checklist affect selection?", answer: "No — organisation only." },
      { question: "Link to calculator?", answer: "/free-redundancy-calculator for pay estimates." },
    ],
  ),
  guidePage(
    "redundancy-role-protection-planner",
    "Redundancy Role Protection Planner",
    "Organise role evidence, redeployment options, alternative-role questions and consultation notes in a structured planner.",
    "Redundancy role protection planner",
    "Role Protection Planner",
    "The Role Protection Planner in the full report structures role evidence, redeployment options and consultation notes week by week — this page explains what to capture.",
    "Product page for the paid Role Protection Planner — not generic selection advice.",
    [
      "Map role achievements and visibility.",
      "Track consultation meetings and actions.",
      "Organise redeployment options.",
      "Link to package and runway modelling.",
    ],
    "Example: weekly planner",
    "Each week note HR meetings, evidence gathered, vacancies applied for and updated pay assumptions.",
    [
      { question: "Is the planner in the paid report?", answer: `Yes — the Role Protection Planner unlocks with the ${RUNWAY_REPORT_FULL} (£${RUNWAY_REPORT_PRICE_GBP}).` },
      { question: "Does it keep my job safe?", answer: "No. It organises preparation and modelling — not outcomes." },
      { question: "Free starting point?", answer: "Yes — statutory estimate and baseline runway on the free calculator." },
    ],
  ),
  guidePage(
    "how-to-find-alternative-role-during-redundancy",
    "How to Find an Alternative Role During Redundancy",
    "Prepare a calm alternative-role search plan with internal vacancies, skills evidence, redeployment questions and deadlines.",
    "How to find an alternative role during redundancy",
    "Find alternative role",
    "Search calmly — internal vacancies first, then skills mapping, then questions to HR about support and timing.",
    "Alternative role search prep.",
    [
      "Prioritise internal vacancies during consultation.",
      "Update CV for internal applications.",
      "Ask HR about redeployment support.",
      "Model finances if search fails.",
    ],
    "Example: two-track plan",
    "Track internal applications separately from external search so you meet employer redeployment expectations while keeping options open.",
    [
      { question: "Does this find jobs for me?", answer: "No. It organises your search approach and financial modelling." },
      { question: "Skills pages?", answer: "See skills selection criteria prep in this guide cluster." },
      { question: "Runway?", answer: "Model months of cover in the calculator." },
    ],
  ),
  guidePage(
    "bonus-commission-redundancy-pay",
    "Bonus and Commission in Redundancy Pay UK",
    "Check whether bonus or commission may belong in your redundancy package model and how missing lines affect your total.",
    "Bonus and commission redundancy pay",
    "Bonus & commission",
    "Bonus and commission are often overlooked in quick mental totals — confirm what your contract and policy say about payment on termination.",
    "Package component page for bonus/commission.",
    [
      "Check contract terms for bonus on termination.",
      "Ask HR about commission earned but unpaid.",
      "Add confirmed figures to package model.",
      "See runway impact of higher totals.",
    ],
    "Example: missing commission",
    "If Q4 commission was earned before notice, ask whether it appears in final pay or redundancy settlement.",
    [
      { question: "Are bonuses always included?", answer: "Depends on contract and scheme rules — verify in writing." },
      { question: "Tax treatment?", answer: "Bonus and commission may be taxed differently from statutory redundancy — check payslips." },
      { question: "Missing money checklist?", answer: "Unlocks in the full private report." },
    ],
    "package",
  ),
  guidePage(
    "unpaid-wages-after-redundancy",
    "Unpaid Wages After Redundancy UK",
    "Check final pay, unpaid wages and deductions that may still be owed after redundancy and include them in your package model.",
    "Unpaid wages after redundancy",
    "Unpaid wages",
    "Redundancy settlements sometimes omit final wages, overtime or expenses — list what should appear on your final payslip.",
    "Unpaid wages package component page.",
    [
      "List expected final pay components.",
      "Compare payslip to written settlement.",
      "Note expenses or overtime still owed.",
      "Add confirmed amounts to calculator.",
    ],
    "Example: final payslip check",
    "Compare your last payslip to HR's settlement letter line by line — notice, holiday, bonus and expense reimbursements.",
    [
      { question: "What if employer does not pay?", answer: "See employer insolvency and government claim pages in this site cluster." },
      { question: "Can I model total package?", answer: "Yes — add manual lines in the wizard." },
      { question: "Legal debt advice?", answer: "This site does not provide debt or legal advice." },
    ],
    "package",
  ),
];
